package com.socklet.smritisaathi.domain.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.LocalContext
import com.socklet.smritisaathi.data.datastore.DataStoreManager
import dagger.hilt.android.EntryPointAccessors
import dagger.hilt.EntryPoint
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent

data class AppStrings(
    val appName: String,
    val appTagline: String,

    // Language & Role Selection
    val selectLanguageTitle: String,
    val selectLanguageSubtitle: String,
    val whoAreYouTitle: String,
    val whoAreYouSubtitle: String,
    val rolePatientTitle: String,
    val rolePatientDesc: String,
    val roleFamilyTitle: String,
    val roleFamilyDesc: String,
    val roleDoctorTitle: String,
    val roleDoctorDesc: String,
    val demoModeButton: String,

    // Patient Today Screen
    val greetingMorning: String,
    val greetingAfternoon: String,
    val greetingEvening: String,
    val todayActivityPrompt: String,
    val start10MinActivity: String,
    val feelingConfusedButton: String,
    val emergencySosButton: String,
    val playInviteReceived: String,

    // Medication & Routine
    val medicationTitle: String,
    val buttonTaken: String,
    val buttonRemindLater: String,
    val buttonNeedHelp: String,

    // Games
    val cardMatchingTitle: String,
    val dailyRoutineTitle: String,
    val faceRecognitionTitle: String,
    val pairsFound: String,
    val checkOrder: String,
    val whoIsThis: String,
    val greatJob: String,

    // Caregiver Dashboard
    val caregiverCommandCenter: String,
    val cognitiveScore: String,
    val medAdherence: String,
    val playInvite: String,
    val sendNudge: String,
    val calmMode: String,
    val pairingCodeLabel: String,
    val familyInviteCodeLabel: String,

    // Doctor Portal
    val doctorPortalTitle: String,
    val assignedPatients: String,
    val clinicalNotes: String,
    val normalStatus: String,
    val attentionNeeded: String,
    val highRisk: String
)

val EnglishStrings = AppStrings(
    appName = "SmritiSaathi",
    appTagline = "Your Memory Companion",
    selectLanguageTitle = "Select Your Language",
    selectLanguageSubtitle = "Tap the speaker icon to hear a voice sample",
    whoAreYouTitle = "Who are you?",
    whoAreYouSubtitle = "Select your role to continue",
    rolePatientTitle = "Patient",
    rolePatientDesc = "I am using this app for myself",
    roleFamilyTitle = "Family Member",
    roleFamilyDesc = "I am caring for a loved one",
    roleDoctorTitle = "Doctor / Health Worker",
    roleDoctorDesc = "I am monitoring patients",
    demoModeButton = "⚡ Instant Demo Mode",
    greetingMorning = "Good morning",
    greetingAfternoon = "Good afternoon",
    greetingEvening = "Good evening",
    todayActivityPrompt = "Here is your gentle brain exercise for today",
    start10MinActivity = "Start Your 10-Minute Activity 🌸",
    feelingConfusedButton = "I feel confused / Calm me 🕊️",
    emergencySosButton = "SOS Emergency 🆘",
    playInviteReceived = "wants to play a game with you! 🎮",
    medicationTitle = "Time for your scheduled medicine",
    buttonTaken = "Taken ✅",
    buttonRemindLater = "Remind me in 15 mins ⏰",
    buttonNeedHelp = "I need help 🆘",
    cardMatchingTitle = "Matching Pairs Game",
    dailyRoutineTitle = "Order Daily Routine",
    faceRecognitionTitle = "Family Face Recognition",
    pairsFound = "Pairs Found",
    checkOrder = "Check Order ✅",
    whoIsThis = "Who is this lovely person?",
    greatJob = "Great job exercising your memory! 🌟",
    caregiverCommandCenter = "Caregiver Command Center",
    cognitiveScore = "Cognitive Score",
    medAdherence = "Med Adherence",
    playInvite = "Play Invite",
    sendNudge = "Send Nudge",
    calmMode = "Calm Mode",
    pairingCodeLabel = "Patient Device Code",
    familyInviteCodeLabel = "Family Invite Code",
    doctorPortalTitle = "Doctor Clinical Portal",
    assignedPatients = "Assigned Patients Triage",
    clinicalNotes = "Clinical Observations",
    normalStatus = "Stable",
    attentionNeeded = "Moderate Monitor",
    highRisk = "High Care Tier"
)

val AssameseStrings = AppStrings(
    appName = "স্মৃতিসাথী",
    appTagline = "আপোনাৰ স্মৃতিৰ বিশ্বস্ত সংগী",
    selectLanguageTitle = "আপোনাৰ ভাষা বাছক",
    selectLanguageSubtitle = "মাতৰ নমুনা শুনিবলৈ স্পীকাৰত টিপক",
    whoAreYouTitle = "আপুনি কোন?",
    whoAreYouSubtitle = "আগবাঢ়িবলৈ আপোনাৰ ভূমিকা বাছক",
    rolePatientTitle = "ৰোগী / জ্যেষ্ঠজন",
    rolePatientDesc = "মই মোৰ বাবে এই এপ ব্যৱহাৰ কৰিছোঁ",
    roleFamilyTitle = "পৰিয়ালৰ সদস্য",
    roleFamilyDesc = "মই মোৰ আপোনজনক চোৱাচিতা কৰিছোঁ",
    roleDoctorTitle = "চিকিৎসক / স্বাস্থ্যকৰ্মী",
    roleDoctorDesc = "মই ৰোগী নিৰীক্ষণ কৰিছোঁ",
    demoModeButton = "⚡ ডেমো মোড চাওক",
    greetingMorning = "শুভ প্ৰভাত",
    greetingAfternoon = "শুভ অপৰাহ্ন",
    greetingEvening = "শুভ সন্ধিয়া",
    todayActivityPrompt = "আজিৰ সহজ মগজুৰ অনুশীলন ইয়াত আছে",
    start10MinActivity = "১০ মিনিটৰ কাৰ্য্যকলাপ আৰম্ভ কৰক 🌸",
    feelingConfusedButton = "মই বিভ্ৰান্ত বোধ কৰিছোঁ 🕊️",
    emergencySosButton = "জৰুৰীকালীন সহায় 🆘",
    playInviteReceived = "আপোনাৰ সৈতে এটা খেল খেলিব বিচাৰে! 🎮",
    medicationTitle = "আপোনাৰ নিয়মীয়া ঔষধৰ সময় হৈছে",
    buttonTaken = "খালোঁ ✅",
    buttonRemindLater = "১৫ মিনিট পিছত সোঁৱৰাব ⏰",
    buttonNeedHelp = "মোক সহায় লাগে 🆘",
    cardMatchingTitle = "যোৰ মিলোৱা খেল",
    dailyRoutineTitle = "দৈনন্দিন কামৰ ক্ৰম",
    faceRecognitionTitle = "পৰিয়ালৰ মুখ চিনাক্তকৰণ",
    pairsFound = "মিলা যোৰ",
    checkOrder = "ক্ৰম পৰীক্ষা কৰক ✅",
    whoIsThis = "এই মৰমিয়াল ব্যক্তিজন কোন?",
    greatJob = "স্মৃতি শক্তিৰ সুন্দৰ অনুশীলন হ'ল! 🌟",
    caregiverCommandCenter = "পৰিয়ালৰ তত্ত্বাৱধান কেন্দ্ৰ",
    cognitiveScore = "স্মৃতিৰ অগ্ৰগতি",
    medAdherence = "ঔষধ খোৱাৰ হাৰ",
    playInvite = "খেলৰ নিমন্ত্ৰণ",
    sendNudge = "বাৰ্তা পঠিয়াওক",
    calmMode = "শান্ত পৰিৱেশ",
    pairingCodeLabel = "ৰোগীৰ মোবাইল কোড",
    familyInviteCodeLabel = "পৰিয়ালৰ ভাগ-বতৰা কোড",
    doctorPortalTitle = "চিকিৎসক পৰ্টেল",
    assignedPatients = "নিৰীক্ষণত থকা ৰোগী তালিকা",
    clinicalNotes = "চিকিৎসাগত পৰ্যবেক্ষণ",
    normalStatus = "সুস্থিৰ",
    attentionNeeded = "নজৰ ৰাখক",
    highRisk = "বিশেষ যত্ন প্ৰয়োজন"
)

val HindiStrings = AppStrings(
    appName = "स्मृतिसाथी",
    appTagline = "आपका आत्मीय स्मृति साथी",
    selectLanguageTitle = "अपनी भाषा चुनें",
    selectLanguageSubtitle = "आवाज़ सुनने के लिए स्पीकर आइकन दबाएं",
    whoAreYouTitle = "आप कौन हैं?",
    whoAreYouSubtitle = "आगे बढ़ने के लिए अपनी भूमिका चुनें",
    rolePatientTitle = "वरिष्ठ / रोगी",
    rolePatientDesc = "मैं स्वयं के लिए ऐप उपयोग कर रहा हूँ",
    roleFamilyTitle = "परिवार का सदस्य",
    roleFamilyDesc = "मैं अपने प्रियजन की देखभाल कर रहा हूँ",
    roleDoctorTitle = "डॉक्टर / स्वास्थ्य कार्यकर्ता",
    roleDoctorDesc = "मैं मरीजों की निगरानी कर रहा हूँ",
    demoModeButton = "⚡ त्वरित डेमो मोड",
    greetingMorning = "सुप्रभात",
    greetingAfternoon = "शुभ दोपहर",
    greetingEvening = "शुभ संध्या",
    todayActivityPrompt = "आज का हल्का मानसिक अभ्यास यहाँ है",
    start10MinActivity = "10 मिनट की गतिविधि शुरू करें 🌸",
    feelingConfusedButton = "मुझे बेचैनी है / शांत करें 🕊️",
    emergencySosButton = "आपातकालीन सहायता 🆘",
    playInviteReceived = "आपके साथ खेल खेलना चाहते हैं! 🎮",
    medicationTitle = "दवा लेने का समय हो गया है",
    buttonTaken = "ले ली ✅",
    buttonRemindLater = "15 मिनट बाद याद दिलाएं ⏰",
    buttonNeedHelp = "मदद चाहिए 🆘",
    cardMatchingTitle = "जोड़ी मिलाओ खेल",
    dailyRoutineTitle = "दैनिक दिनचर्या क्रम",
    faceRecognitionTitle = "परिवार पहचान खेल",
    pairsFound = "मिली जोड़ियाँ",
    checkOrder = "क्रम जाँचें ✅",
    whoIsThis = "यह आत्मीय व्यक्ति कौन हैं?",
    greatJob = "स्मृति का बहुत सुंदर अभ्यास हुआ! 🌟",
    caregiverCommandCenter = "देखभाल कमांड सेंटर",
    cognitiveScore = "संज्ञानात्मक स्कोर",
    medAdherence = "दवा पालन दर",
    playInvite = "खेल का न्योता",
    sendNudge = "संदेश भेजें",
    calmMode = "शांत मोड",
    pairingCodeLabel = "मरीज डिवाइस कोड",
    familyInviteCodeLabel = "पारिवारिक कोड",
    doctorPortalTitle = "चिकित्सक पोर्टल",
    assignedPatients = "अस्पताल मरीज सूची",
    clinicalNotes = "चिकित्सकीय नोट्स",
    normalStatus = "स्थिर",
    attentionNeeded = "मध्यम निगरानी",
    highRisk = "विशेष देखभाल"
)

val BengaliStrings = AppStrings(
    appName = "স্মৃতিসাথী",
    appTagline = "আপনার স্মৃতির বিশ্বস্ত সঙ্গী",
    selectLanguageTitle = "আপনার ভাষা নির্বাচন করুন",
    selectLanguageSubtitle = "আওয়াজ শুনতে স্পিকার আইকনে ট্যাপ করুন",
    whoAreYouTitle = "আপনি কে?",
    whoAreYouSubtitle = "এগিয়ে যেতে আপনার ভূমিকা নির্বাচন করুন",
    rolePatientTitle = "রোগী / জ্যেষ্ঠ",
    rolePatientDesc = "আমি আমার জন্য এই অ্যাপ ব্যবহার করছি",
    roleFamilyTitle = "পরিবারের সদস্য",
    roleFamilyDesc = "আমি আমার প্রিয়জনের যত্ন নিচ্ছি",
    roleDoctorTitle = "ডাক্তার / স্বাস্থ্যকর্মী",
    roleDoctorDesc = "আমি রোগীদের পর্যবেক্ষণ করছি",
    demoModeButton = "⚡ ডেমো মোড দেখুন",
    greetingMorning = "শুভ সকাল",
    greetingAfternoon = "শুভ দুপুর",
    greetingEvening = "শুভ সন্ধ্যা",
    todayActivityPrompt = "আজকের হালকা মানসিক অনুশীলন এখানে",
    start10MinActivity = "১০ মিনিটের কার্যকলাপ শুরু করুন 🌸",
    feelingConfusedButton = "আমি বিভ্রান্ত বোধ করছি 🕊️",
    emergencySosButton = "জরুরি সহায়তা 🆘",
    playInviteReceived = "আপনার সাথে একটি গেম খেলতে চায়! 🎮",
    medicationTitle = "ঔষধ নেওয়ার সময় হয়েছে",
    buttonTaken = "নিয়েছি ✅",
    buttonRemindLater = "১৫ মিনিট পরে মনে করিয়ে দিন ⏰",
    buttonNeedHelp = "আমার সাহায্য দরকার 🆘",
    cardMatchingTitle = "জোড়া মেলানো খেলা",
    dailyRoutineTitle = "দৈনন্দিন রুটিন ক্রম",
    faceRecognitionTitle = "পরিবারের মুখ চেনা খেলা",
    pairsFound = "মেলা জোড়া",
    checkOrder = "ক্রম পরীক্ষা করুন ✅",
    whoIsThis = "এই স্নেহময় ব্যক্তি কে?",
    greatJob = "স্মৃতিশক্তির সুন্দর অনুশীলন! 🌟",
    caregiverCommandCenter = "যত্ন কমান্ড সেন্টার",
    cognitiveScore = "জ্ঞানীয় স্কোর",
    medAdherence = "ঔষধ পালন হার",
    playInvite = "খেলার আমন্ত্রণ",
    sendNudge = "বার্তা পাঠান",
    calmMode = "শান্ত মোড",
    pairingCodeLabel = "রোগী ডিভাইস কোড",
    familyInviteCodeLabel = "পারিবারিক কোড",
    doctorPortalTitle = "ডাক্তার পোর্টাল",
    assignedPatients = "নির্ধারিত রোগী তালিকা",
    clinicalNotes = "ক্লিনিক্যাল নোটস",
    normalStatus = "স্থিতিশীল",
    attentionNeeded = "মধ্যম পর্যবেক্ষণ",
    highRisk = "বিশেষ যত্ন"
)

val MizoStrings = AppStrings(
    appName = "SmritiSaathi",
    appTagline = "I hre chiana i kul",
    selectLanguageTitle = "I tawng tihpui la",
    selectLanguageSubtitle = "Hriatna tur lo speaker icon ah tap la",
    whoAreYouTitle = "Nang eng nge ni?",
    whoAreYouSubtitle = "I hna tur i role tihpui la",
    rolePatientTitle = "Patient / Piase",
    rolePatientDesc = "Ka tan ka app hi ka hmepui ve",
    roleFamilyTitle = "Familia mi",
    roleFamilyDesc = "Ka inna mi ka enkul ve",
    roleDoctorTitle = "Doctor / Health Worker",
    roleDoctorDesc = "Patient te ka enkul ve",
    demoModeButton = "⚡ Demo en tur",
    greetingMorning = "Lawmna tha",
    greetingAfternoon = "Thla tha",
    greetingEvening = "Zan tha",
    todayActivityPrompt = "Tunin i hritna tur hmalak phek a awm",
    start10MinActivity = "10 minute activity tan la 🌸",
    feelingConfusedButton = "Ka hre chiana ka buai 🕊️",
    emergencySosButton = "Emergency help 🆘",
    playInviteReceived = "I in a game hi a play duh! 🎮",
    medicationTitle = "Sachhi tur time a la tir",
    buttonTaken = "Ka lo la ✅",
    buttonRemindLater = "10 minute hnu ah hriatna pe leh ⏰",
    buttonNeedHelp = "Ka tanpui a ngai 🆘",
    cardMatchingTitle = "Pair matching game",
    dailyRoutineTitle = "Tinthlan routine order",
    faceRecognitionTitle = "Familia hming chhiatna",
    pairsFound = "Pairs matched",
    checkOrder = "Order check la ✅",
    whoIsThis = "He mi hmangaih hi eng nge ni?",
    greatJob = "I hre chiana i tan tha hle! 🌟",
    caregiverCommandCenter = "Caregiver Command Center",
    cognitiveScore = "Cognitive Score",
    medAdherence = "Medicine palna rate",
    playInvite = "Game invite",
    sendNudge = "Message send la",
    calmMode = "Calm mode",
    pairingCodeLabel = "Patient device code",
    familyInviteCodeLabel = "Familia code",
    doctorPortalTitle = "Doctor Portal",
    assignedPatients = "Assigned patient list",
    clinicalNotes = "Clinical notes",
    normalStatus = "Stable",
    attentionNeeded = "Medium monitor",
    highRisk = "Special care"
)

val KhasiStrings = AppStrings(
    appName = "SmritiSaathi",
    appTagline = "Phi u ka jingialang phi",
    selectLanguageTitle = "Pili ka ktien phi",
    selectLanguageSubtitle = "Shapuri speaker icon man biang",
    whoAreYouTitle = "Nga dei?",
    whoAreYouSubtitle = "Pili ka role biang ban",
    rolePatientTitle = "Patient / Kyndong",
    rolePatientDesc = "Nga ka wan ka app khatna",
    roleFamilyTitle = "Shapoh mi",
    roleFamilyDesc = "Nga ka care ka jingialang",
    roleDoctorTitle = "Doctor / Health Worker",
    roleDoctorDesc = "Nga ka monitor ki patient",
    demoModeButton = "⚡ Demo mode ei",
    greetingMorning = "Khublei sngi",
    greetingAfternoon = "Khublei met",
    greetingEvening = "Khublei san",
    todayActivityPrompt = "Ka sngi khatna ka jingthoh shisha",
    start10MinActivity = "10 minute activity pynshan 🌸",
    feelingConfusedButton = "Nga jingbuh 🕊️",
    emergencySosButton = "Emergency help 🆘",
    playInviteReceived = "U wan ka game! 🎮",
    medicationTitle = "Time kawei ka medicine",
    buttonTaken = "Ka la don ✅",
    buttonRemindLater = "10 minute kawei jingthoh ⏰",
    buttonNeedHelp = "Nga kwah help 🆘",
    cardMatchingTitle = "Pair matching game",
    dailyRoutineTitle = "Daily routine order",
    faceRecognitionTitle = "Shapoh face recognition",
    pairsFound = "Pairs pynmih",
    checkOrder = "Order check ✅",
    whoIsThis = "Ka dei kawei ka mi?",
    greatJob = "Phi tha hune! 🌟",
    caregiverCommandCenter = "Caregiver Command Center",
    cognitiveScore = "Cognitive Score",
    medAdherence = "Medicine adherence",
    playInvite = "Game invite",
    sendNudge = "Message send",
    calmMode = "Calm mode",
    pairingCodeLabel = "Patient device code",
    familyInviteCodeLabel = "Shapoh code",
    doctorPortalTitle = "Doctor Portal",
    assignedPatients = "Assigned patient list",
    clinicalNotes = "Clinical notes",
    normalStatus = "Stable",
    attentionNeeded = "Medium monitor",
    highRisk = "Special care"
)

fun getAppStringsForLanguage(code: String): AppStrings {
    return when (code.lowercase()) {
        "as" -> AssameseStrings
        "hi" -> HindiStrings
        "bn" -> BengaliStrings
        "lus" -> MizoStrings
        "kha" -> KhasiStrings
        "mni" -> AssameseStrings // Manipuri uses Assamese script
        "gar" -> BengaliStrings // Garo uses Bengali script
        "brx" -> HindiStrings // Bodo uses Devanagari
        "nmx" -> EnglishStrings // Nagamese uses English
        else -> EnglishStrings
    }
}
